### ISSUE TITLE
Add default mosquitto.conf file in local install

### ISSUE THREAD

**Issue by knolleary** [flowforge/installer#50]
### Description

**As a:** first time user

**I want to:** a default mosquitto configuration file to be provided

**So that:** I have less to do

---

Our install instructions leave the user with a lot of work to do around mosquitto. A quick win will be for the installer to create a `etc/mosquitto.conf` file with our default configuration in.

The file should include suitable comments to highlight the entries that they will need to modify for their environment - although the defaults should largely just work. 

I *think* the tricker one will be the path to the auth plugin. We should get more opinionated about where that should be - as the docs currently leave it completely up to the user to chose.

### Acceptance Criteria

- [x] After running the installer, there is a default `mosquitto.conf` file
- [x] Install docs updated (both here and in main docs) to reflect improved process

**Comment by knolleary** [comment]
With #52 merged, we need to update the install docs to reflect the fact the file is now provided.

**Comment by hardillb** [comment]
I'll look at the docs now

**Comment by knolleary** [comment]
Default config file added and install docs updated.
