### ISSUE TITLE
Installer ignores suggested default option for user choice (current or Flowforge) and bails when user hits enter

### ISSUE THREAD

**Issue by tyeth** [flowforge/installer#71]
### Current Behavior

Installer asks three questions during installation and the linux convention is that the uppercase option is default, and if the user submits empty input then that default option is used.
This doesn't work properly for the last question (and potentially others), the installer then bails and the user is left unaware how to proceed except to reinstall.

### Expected Behavior

As expected with the capitol option being accepted as user default, and the option to use the Flowforge user is chosen when the user just hits enter with no other input.

### Steps To Reproduce

On a pi 3A+ (512mb with 2/5ghz wifi), be patient as it appears to stall during npm but is just slow.

Run installer on fresh copy of raspberry pi OS 32bit headless.
Accept first question to install NodeJS, then expect following output (truncated):
```
Installing latest Node-RED as a stack
**************************************************************
installing stack node-red@latest
node-red@latest is currently node-red@3.0.2
installed stack node-red@3.0.2
**************************************************************
 Do you want to run FlowForge as a service?
**************************************************************
Y/n: y
**************************************************************
 Do you want to run FlowForge as the current user (pi)   
 or create a flowforge user?                                
**************************************************************
Current/FlowForge (c/F): 
**************************************************************
 Not C or F                                                  
**************************************************************
pi@rpi3a0001:/opt/flowforge $ 
```

### Environment

- FlowForge version: latest install instructions + zip

**Comment by hardillb** [comment]
It's missing a block to set the default

https://github.com/flowforge/installer/blob/0d52cb8b3201d09561c3ed51d2755e114feea772/install.sh#L208-L213

should be:

```
      read -p "Current/FlowForge (c/F): " cf
      if [ -z "${cf}" ]; then
          cf=F
      fi
      if [[ "$cf" == "c" ]] || [[ "$cf" == "C" ]]; then


        FF_USER=`id -u -n`
        FF_GROUP=`id -g -n`
```

**Comment by hardillb** [comment]
Fix should hopefully go out with the next release on Thursday
